include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - [build/**]
    - '**/*.g.dart'

  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    - cancel_subscriptions
    - use_key_in_widget_constructors
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
